job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-bulgaria
    APP_HOSTPATH: bulgaria
    WP_DB_NAME_PREFIX: planet4-bulgaria_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-bulgaria
    NEWRELIC_APPNAME: P4 Bulgaria Development
    WP_DB_NAME: planet4-bulgaria_wordpress_develop
    WP_STATELESS_BUCKET: planet4-bulgaria-stateless-develop
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: release.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: bulgaria
    HELM_RELEASE: planet4-bulgaria-release
    NEWRELIC_APPNAME: P4 Bulgaria Release
    WP_DB_NAME: planet4-bulgaria_wordpress_release
    WP_STATELESS_BUCKET: planet4-bulgaria-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: master.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: bulgaria
    HELM_RELEASE: planet4-bulgaria-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Bulgaria Production
    WP_DB_NAME: planet4-bulgaria_wordpress_master
    WP_STATELESS_BUCKET: planet4-bulgaria-stateless